// sync-combined-audio-chat/vue/src/App.vue
<script setup lang="ts">
import { onMounted, onBeforeUnmount } from "vue";
import {
  createClientWithPublishableKey,
  type Client,
} from "@aircore/aircore-panel-core";
import { MediaPanel, type MediaPanelType } from "@aircore/aircore-media-panel";
import { ChatPanel, type ChatPanelType } from "@aircore/aircore-chat-panel";

const channelId = "YOUR_CHANNEL_ID";
const userId = "YOUR_USER_ID" + Math.random();
const publishableApiKey = import.meta.env.VITE_PUBLISHABLE_API_KEY as string; // get your api key on https://developer.aircore.io

let myMediaPanel: MediaPanelType | null = null;
let myChatPanel: ChatPanelType | null = null;

let client: Client | null = null;

onMounted(() => {
  client = createClientWithPublishableKey(publishableApiKey, userId);
  client.setUserDisplayName("John Doe");
  client.setUserAvatarUrl("https://picsum.photos/200/200");
  client.connect(channelId);

  myMediaPanel = MediaPanel("#my-combined-panel", {
    client,
    channelId,
  });

  myChatPanel = ChatPanel(null, {
    client,
    channelId,
  });

  myMediaPanel.combine(myChatPanel);
});

onBeforeUnmount(() => {
  myMediaPanel?.destroy();
  myChatPanel?.destroy();
  client?.disconnect(channelId);
});
</script>

<template>
  <div id="my-combined-panel" />
</template>

// sync-combined-audio-chat/react/src/App.tsx
import { MediaPanel } from '@aircore/aircore-media-panel';
import { ChatPanel } from '@aircore/aircore-chat-panel';
import { createClientWithPublishableKey } from '@aircore/aircore-panel-core';
import { useEffect } from 'react';
import './App.css';

const publishableApiKey = 'ADD_YOUR_PUBLISHABLE_API_KEY_HERE'; // get your api key on https://developer.aircore.io
const channelId = 'YOUR_CHANNEL_ID';
const userId = 'YOUR_USER_ID' + Math.floor(Math.random() * 1000);

const Home = () => {
  useEffect(() => {
    const client = createClientWithPublishableKey(publishableApiKey, userId)
    client.setUserDisplayName("John Doe");
    client.setUserAvatarUrl("https://picsum.photos/200/200");
    client.connect(channelId);

    const mediaPanel = MediaPanel(
      '#my-combined-panel',
      {
        client,
        channelId,
      }
    );

    const chatPanel = ChatPanel(
      null,
      {
        client,
        channelId,
      }
    );

    mediaPanel.combine(chatPanel);

    return () => {
      client.disconnect(channelId);
      mediaPanel.destroy();
      chatPanel.destroy();
    }
  }, []);

  return (
    <div className="container">
      <div id="my-combined-panel" />
    </div>
  )
}

export default Home
